name: torrent-search

x-networks: &default-networks
  networks:
    torrent-network:
  dns:
    - 127.0.0.11 # Docker embedded DNS
    - 9.9.9.9
    - 149.112.112.112
    - 2620:fe::fe
    - 2620:fe::9

networks:
  torrent-network:
    name: torrent-network
    driver: bridge

x-logging: &default-logging
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"

services:
  torrent-search-build:
    container_name: torrent-search-build
    image: torrent-search-mcp
    build: .
    command: ["echo", "build completed"]
    <<: [*default-logging]

  torrent-search-api:
    container_name: torrent-search-api
    image: torrent-search-mcp
    restart: unless-stopped
    init: true
    depends_on:
      torrent-search-build:
        condition: service_started
        required: true
    ports:
      - 8000:8000
    command: ["torrent-search-mcp", "--mode", "fastapi"]
    env_file:
      - path: .env
        required: false
    <<: [*default-networks, *default-logging]

  torrent-search-mcp:
    container_name: torrent-search-mcp
    image: torrent-search-mcp
    restart: unless-stopped
    init: true
    depends_on:
      torrent-search-build:
        condition: service_started
        required: true
      torrent-search-api:
        condition: service_started
    ports:
      - 8001:8000
    command: ["torrent-search-mcp", "--mode", "http"]
    env_file:
      - path: .env
        required: false
    environment:
      TORRENT_SEARCH_API_URL: http://torrent-search-api:8000
    <<: [*default-networks, *default-logging]
