name: torrent-search

x-dns: &default-dns
  dns:
    - 9.9.9.9
    - 149.112.112.112
    - 2620:fe::fe
    - 2620:fe::9

x-logging: &default-logging
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"

services:
  ygg-api:
    image: ghcr.io/djerayane/ygege:docker-publish
    container_name: ygg-api
    restart: unless-stopped
    ports:
      - 8715:8715
    volumes:
      - ygg-config:/config
    #environment:
    # BIND_IP: "0.0.0.0"                   # Optional: IP to bind (default: 0.0.0.0)
    # BIND_PORT: "8715"                    # Optional: Internal port (default: 8715)
    # LOG_LEVEL: "info"                    # Optional: Log level (default: info)
    # TMDB_TOKEN: "your_token"             # Optional: TMDB API token for IMDB/TMDB lookups
    # RELAY_URL: "wss://relay.ygg.gratis"  # Optional: Nostr relay URL (default: wss://relay.ygg.gratis)
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8715/health || exit 1" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s
    <<: [ *default-dns, *default-logging ]
    network_mode: bridge
    deploy:
      replicas: ${YGG_ENABLE:-1}

  torrent-search-mcp:
    container_name: torrent-search-mcp
    build: .
    image: torrent-search-mcp
    restart: unless-stopped
    ports:
      - 8000:8000
    environment:
      - YGG_LOCAL_API=http://ygg-api:8715
    env_file:
      - .env
    volumes:
      - torrents:/app/${FOLDER_TORRENT_FILES:-torrents}
    <<: [ *default-dns, *default-logging ]
    network_mode: bridge

volumes:
  torrents:
  ygg-config:
