FROM ghcr.io/astral-sh/uv:python3.14-trixie-slim AS runner
ENV UV_PYTHON_DOWNLOADS=0
RUN apt-get update && \
    uvx playwright install --with-deps chromium && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
RUN pip install --upgrade pip
ARG VERSION
RUN pip install torrent-search-mcp==$VERSION
EXPOSE 8000