name: torrent-search-mcp

services:
  torrent-search-mcp:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: torrent-search-mcp
    container_name: torrent-search-mcp
    ports:
      - 8765:8000
    env_file:
      - ../.env
    dns:
      - 9.9.9.9
      - 149.112.112.112
      - 2620:fe::fe
      - 2620:fe::9
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"